# -*- coding: utf-8 -*-
"""MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZwYj1Sxsz4v_d8ULn5gJw9p9Tf2DhV0
"""

import kagglehub


path = kagglehub.dataset_download("rakkesharv/real-estate-data-from-7-indian-cities")

print("Path to dataset files:", path)

import os

dataset_path = path
print(f"Contents of the dataset directory '{dataset_path}':")
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 4 * (level + 1)
    for f in files:
        print(f'{subindent}{f}')

import pandas as pd

csv_file_path = os.path.join(dataset_path, 'Real Estate Data V21.csv')

df = pd.read_csv(csv_file_path)

print(df.head())
print(df.info())

with open(csv_file_path, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 10:
            break
        print(line.strip())

"""### Data Preprocessing


"""

import pandas as pd
import os
import numpy as np
import kagglehub
import re


try:
    _ = path
except NameError:
    path = kagglehub.dataset_download("rakkesharv/real-estate-data-from-7-indian-cities")

csv_file_name = 'Real Estate Data V21.csv'
csv_file_path = None

for root, dirs, files in os.walk(path):
    if csv_file_name in files:
        csv_file_path = os.path.join(root, csv_file_name)
        break

if csv_file_path is None:
    raise FileNotFoundError(f"Could not find '{csv_file_name}' in '{path}' or its subdirectories.")

df = pd.read_csv(csv_file_path)

def clean_price(price_str):
    price_str = str(price_str).replace('₹', '').strip()
    if 'Cr' in price_str:
        return float(price_str.replace('Cr', '')) * 1_00_00_000
    elif 'acs' in price_str.lower():
        return np.nan
    elif 'L' in price_str:
        return float(price_str.replace('L', '')) * 1_00_000
    else:
        try:
            return float(price_str)
        except ValueError:
            return np.nan

df['Price'] = df['Price'].apply(clean_price)

def extract_bhk(title):
    match = re.search(r'(\d+)\s*BHK', title, re.IGNORECASE)
    if match:
        return int(match.group(1))
    return np.nan

def extract_kitchen_presence(description):
    if isinstance(description, str) and 'kitchen' in description.lower():
        return 1
    return 0

df['BHK'] = df['Property Title'].apply(extract_bhk)
df['Has_Kitchen'] = df['Description'].apply(extract_kitchen_presence)

df['Balcony'] = df['Balcony'].map({'Yes': 1, 'No': 0})

df_processed = df.drop(columns=['Name', 'Description', 'Property Title'])

df_processed.dropna(subset=['Price'], inplace=True)

if df_processed['BHK'].isnull().any():
    mode_bhk = df_processed['BHK'].mode()[0]
    df_processed['BHK'].fillna(mode_bhk, inplace=True)
    df_processed['BHK'] = df_processed['BHK'].astype(int)

num_unique_locations = df_processed['Location'].nunique()
print(f"Number of unique locations: {num_unique_locations}")

df_processed = pd.get_dummies(df_processed, columns=['Location'], drop_first=True)

print(df_processed.head())
print(df_processed.info())

"""### Data Splitting

"""

from sklearn.model_selection import train_test_split

X = df_processed.drop('Price', axis=1)
y = df_processed['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### Model Training


"""

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train, y_train)

y_pred_lin_reg = lin_reg_model.predict(X_test)


mae_lin_reg = mean_absolute_error(y_test, y_pred_lin_reg)
mse_lin_reg = mean_squared_error(y_test, y_pred_lin_reg)
rmse_lin_reg = np.sqrt(mse_lin_reg)
r2_lin_reg = r2_score(y_test, y_pred_lin_reg)

print("Linear Regression Model Evaluation:")
print(f"  Mean Absolute Error (MAE): {mae_lin_reg:,.2f}")
print(f"  Mean Squared Error (MSE): {mse_lin_reg:,.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_lin_reg:,.2f}")
print(f"  R-squared (R2): {r2_lin_reg:.4f}")

rf_reg_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_reg_model.fit(X_train, y_train)

y_pred_rf_reg = rf_reg_model.predict(X_test)

mae_rf_reg = mean_absolute_error(y_test, y_pred_rf_reg)
mse_rf_reg = mean_squared_error(y_test, y_pred_rf_reg)
rmse_rf_reg = np.sqrt(mse_rf_reg)
r2_rf_reg = r2_score(y_test, y_pred_rf_reg)

print("\nRandom Forest Regressor Model Evaluation:")
print(f"  Mean Absolute Error (MAE): {mae_rf_reg:,.2f}")
print(f"  Mean Squared Error (MSE): {mse_rf_reg:,.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_rf_reg:,.2f}")
print(f"  R-squared (R2): {r2_rf_reg:.4f}")

from sklearn.ensemble import GradientBoostingRegressor

gb_reg_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
gb_reg_model.fit(X_train, y_train)


y_pred_gb_reg = gb_reg_model.predict(X_test)


mae_gb_reg = mean_absolute_error(y_test, y_pred_gb_reg)
mse_gb_reg = mean_squared_error(y_test, y_pred_gb_reg)
rmse_gb_reg = np.sqrt(mse_gb_reg)
r2_gb_reg = r2_score(y_test, y_pred_gb_reg)

print("\nGradient Boosting Regressor Model Evaluation:")
print(f"  Mean Absolute Error (MAE): {mae_gb_reg:,.2f}")
print(f"  Mean Squared Error (MSE): {mse_gb_reg:,.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_gb_reg:,.2f}")
print(f"  R-squared (R2): {r2_gb_reg:.4f}")

"""### Ensemble Model (Voting Regressor)

"""

from sklearn.ensemble import VotingRegressor

estimators = [
    ('lr', lin_reg_model),
    ('rf', rf_reg_model),
    ('gb', gb_reg_model)
]


ensemble_model = VotingRegressor(estimators=estimators, n_jobs=-1)
ensemble_model.fit(X_train, y_train)

y_pred_ensemble = ensemble_model.predict(X_test)

mae_ensemble = mean_absolute_error(y_test, y_pred_ensemble)
mse_ensemble = mean_squared_error(y_test, y_pred_ensemble)
rmse_ensemble = np.sqrt(mse_ensemble)
r2_ensemble = r2_score(y_test, y_pred_ensemble)

print("\nEnsemble Model (Voting Regressor) Evaluation:")
print(f"  Mean Absolute Error (MAE): {mae_ensemble:,.2f}")
print(f"  Mean Squared Error (MSE): {mse_ensemble:,.2f}")
print(f"  Root Mean Squared Error (RMSE): {rmse_ensemble:,.2f}")
print(f"  R-squared (R2): {r2_ensemble:.4f}")

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


weights_grid_values = [
    (0.1, 0.45, 0.45),
    (0.45, 0.1, 0.45),
    (0.45, 0.45, 0.1),
    (0.33, 0.33, 0.34),
    (0.0, 0.5, 0.5)
]

best_weights = None
best_mse = float('inf')
best_model_found = None

print("Starting manual Grid Search for VotingRegressor weights...")

for weights_tuple in weights_grid_values:
    print(f"Testing weights: {weights_tuple}")


    current_voting_regressor = VotingRegressor(estimators=estimators, weights=weights_tuple, n_jobs=-1)

    try:
        current_voting_regressor.fit(X_train, y_train)


        y_pred_train = current_voting_regressor.predict(X_train)
        current_mse = mean_squared_error(y_train, y_pred_train)

        print(f"  MSE on training data with these weights: {current_mse:,.2f}")

        if current_mse < best_mse:
            best_mse = current_mse
            best_weights = weights_tuple
            best_model_found = current_voting_regressor

    except Exception as e:
        print(f"  Error fitting with weights {weights_tuple}: {e}")


print("\nManual Grid Search Complete.")

if best_weights:
    print(f"Best VotingRegressor Weights: {best_weights}")
    print(f"Best (training) MSE with these weights: {best_mse:,.2f}")

    best_ensemble_model = best_model_found
    y_pred_tuned_ensemble = best_ensemble_model.predict(X_test)

    mae_tuned_ensemble = mean_absolute_error(y_test, y_pred_tuned_ensemble)
    mse_tuned_ensemble = mean_squared_error(y_test, y_pred_tuned_ensemble)
    rmse_tuned_ensemble = np.sqrt(mse_tuned_ensemble)
    r2_tuned_ensemble = r2_score(y_test, y_pred_tuned_ensemble)

    print("\nTuned Ensemble Model (Voting Regressor) Evaluation (on test set):")
    print(f"  Best Weights: {best_weights}")
    print(f"  Mean Absolute Error (MAE): {mae_tuned_ensemble:,.2f}")
    print(f"  Mean Squared Error (MSE): {mse_tuned_ensemble:,.2f}")
    print(f"  Root Mean Squared Error (RMSE): {rmse_tuned_ensemble:,.2f}")
    print(f"  R-squared (R2): {r2_tuned_ensemble:.4f}")
else:
    print("No successful model training found.")